apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq1
  template:
    metadata:
      labels:
        app: rabbitmq1
    spec:
      containers:
      - name: rabbitmq1
        image: rabbitmq:management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "user1"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password1"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq1-service
spec:
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq1
